name: Run Python Script Twice Daily

on:
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *" # Every day at 6pm
  workflow_dispatch: # Manual trigger option

jobs:
  run-python:
    runs-on: ubuntu-latest
    environment: UserDetails

    steps:
      - name: Prepare Env file
        run: echo "STREAK=${{ vars.STREAK }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          STREAK: ${{ vars.STREAK }}
        run: |
          python main.py
